export const IDENTITY_SERVICE_TOKEN: string = 'IDENTITY_SERVICE_TOKEN';
export const STREAMS_SERVICE_TOKEN: string = 'STREAMS_SERVICE_TOKEN';
export const GEOCODING_SERVICE_TOKEN: string = 'GEOCODING_SERVICE_TOKEN';
