import { MigrationInterface, QueryRunner } from "typeorm";

export class updatesBaseEntityTimestampSuffixToOn1676120085842 implements MigrationInterface {
    name = 'updatesBaseEntityTimestampSuffixToOn1676120085842'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "app_claim" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_claim" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_claim" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_device_code" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_device_code" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_device_code" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_address" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_address" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_address" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_profile" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_profile" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_profile" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_role" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_role" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_role" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_tenant" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_tenant" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_tenant" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_account" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_account" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_account" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "geo_location" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "geo_location" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "geo_location" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_client" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "app_client" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "app_client" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "offender" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "offender" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "offender" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "case" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "case" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "case" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "stream_key" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "stream_key" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "stream_key" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "stream" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "stream" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "stream" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "app_claim" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_claim" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_claim" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_device_code" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_device_code" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_device_code" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_address" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_address" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_address" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_profile" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_profile" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_profile" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_role" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_role" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_role" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_tenant" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_tenant" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_tenant" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_account" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_account" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_account" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "geo_location" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "geo_location" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "geo_location" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_client" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_client" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "app_client" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "offender" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "offender" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "offender" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "case" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "case" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "case" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "stream_key" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "stream_key" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "stream_key" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "stream" ADD "created_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "stream" ADD "updated_on" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()`);
        await queryRunner.query(`ALTER TABLE "stream" ADD "deleted_on" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_user" ALTER COLUMN "email_confirmation_token_expiration" SET DEFAULT NOW() + interval '24 hours'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "app_user" ALTER COLUMN "email_confirmation_token_expiration" SET DEFAULT (now() + '24:00:00')`);
        await queryRunner.query(`ALTER TABLE "stream" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "stream" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "stream" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "stream_key" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "stream_key" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "stream_key" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "case" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "case" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "case" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "offender" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "offender" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "offender" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_client" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_client" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_client" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "geo_location" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "geo_location" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "geo_location" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_account" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_account" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_account" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_tenant" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_tenant" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_tenant" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_user" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_role" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_role" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_role" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_profile" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_profile" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_profile" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_address" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_address" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_address" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_device_code" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_device_code" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_device_code" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "app_claim" DROP COLUMN "deleted_on"`);
        await queryRunner.query(`ALTER TABLE "app_claim" DROP COLUMN "updated_on"`);
        await queryRunner.query(`ALTER TABLE "app_claim" DROP COLUMN "created_on"`);
        await queryRunner.query(`ALTER TABLE "stream" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "stream" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stream" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stream_key" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "stream_key" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stream_key" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "case" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "case" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "case" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "offender" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "offender" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "offender" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_client" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_client" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_client" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "geo_location" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "geo_location" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "geo_location" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_account" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_account" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_account" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_tenant" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_tenant" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_tenant" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_user" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_role" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_role" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_role" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_refresh_token" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_profile" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_profile" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_profile" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_address" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_address" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_address" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_device_code" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_device_code" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_device_code" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_claim" ADD "deleted_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "app_claim" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "app_claim" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
    }

}
